language: cpp

addons:
  apt:
    packages:
    - graphviz
    - doxygen
  homebrew:
    packages: 
    - graphviz
    - doxygen
    update: true

before_script:
- mkdir build
- cd build
- cmake ..

script:
- cmake --build . --target all
- cmake --build . --target test
- cmake --build . --target doc
- cmake --build . --target package
- cmake --build . --target dist
- cmake --build . --target package_source

jobs:
  include:
    - os: linux
      dist: focal
    - os: osx
    - os: windows
  allow_failures:
    - os: windows
